# Generated by Django 6.0.3 on 2026-03-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0009_titan_api_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='character',
            name='titan',
        ),
    ]
