# Generated by Django 6.0.3 on 2026-03-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0011_titan_inheritor_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episodes',
        ),
        migrations.AlterField(
            model_name='character',
            name='relatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='aot.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(blank=True, related_name='characters_in_episode', to='aot.episode'),
        ),
    ]
