# Generated by Django 6.0.3 on 2026-03-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0012_remove_character_episodes_alter_character_relatives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='characters',
        ),
        migrations.AlterField(
            model_name='location',
            name='debut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debut_location', to='aot.episode'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='notable_former_inhabitants',
        ),
        migrations.AlterField(
            model_name='organization',
            name='debut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_debuted_in_episode', to='aot.episode'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notable_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_as_notable_member', to='aot.character'),
        ),
        migrations.AddField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='episodes_with_character', to='aot.character'),
        ),
        migrations.AddField(
            model_name='location',
            name='notable_former_inhabitants',
            field=models.ManyToManyField(blank=True, related_name='locations_as_former_inhabitant', to='aot.character'),
        ),
    ]
