# Generated by Django 6.0.3 on 2026-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0013_remove_episode_characters_alter_location_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='relatives',
        ),
        migrations.AddField(
            model_name='character',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='related_characters', to='aot.character'),
        ),
    ]
