# Generated by Django 6.0.3 on 2026-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0014_remove_character_relatives_character_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='notable_former_inhabitants',
        ),
        migrations.RemoveField(
            model_name='location',
            name='notable_inhabitants',
        ),
        migrations.AddField(
            model_name='location',
            name='notable_former_inhabitants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='notable_inhabitants',
            field=models.ManyToManyField(blank=True, related_name='locations_as_former_inhabitant', to='aot.character'),
        ),
    ]
