# Generated by Django 6.0.3 on 2026-03-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0015_remove_location_notable_former_inhabitants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titan',
            name='organization',
        ),
    ]
