# Generated by Django 6.0.3 on 2026-03-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0017_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='notable_members',
        ),
        migrations.AddField(
            model_name='organization',
            name='notable_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizations_as_notable_member', to='aot.character'),
        ),
    ]
