# Generated by Django 6.0.3 on 2026-03-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0018_remove_organization_notable_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notable_members',
            field=models.ManyToManyField(blank=True, related_name='organizations_as_notable_member', to='aot.character'),
        ),
    ]
