# Generated by Django 6.0.3 on 2026-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aot', '0019_alter_organization_notable_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
